# Generated by Django 3.2 on 2026-05-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash On Delivery'), ('NETBANKING', 'Net Banking')], max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
