# Generated by Django 3.2 on 2026-05-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_order_date_order_ordered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_at',
            new_name='order_date',
        ),
    ]
