# Generated by Django 3.2 on 2026-05-10 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20260510_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('seller_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='seller_photos/')),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('market_name', models.CharField(max_length=200)),
                ('vegetables_selling', models.TextField()),
                ('experience', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
