# Generated by Django 3.2 on 2026-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20260511_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
