# Generated by Django 3.2 on 2026-05-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20260511_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
